name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main # Se ejecuta cuando hagas push a la rama main

permissions:
  contents: write # Necesario para que GitHub Actions pueda publicar en gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
